"""The Pst data model: everything a PEST control file holds, as tables.

All routes go through this class: Excel -> Pst -> .pst, .pst -> Pst -> Excel,
.par -> Pst -> Excel.  `validate()` is the one place that checks consistency
(duplicate names, tied targets, undefined groups, dangling prior equations).
"""
import os
import re
import warnings

import numpy as np
import pandas as pd

from .sections import COMPUTED, FIELD_SECTION, _num, fmt, is_number, normalize_mode

PAR_COLS = 'PARNME PARTRANS PARCHGLIM PARVAL1 PARLBND PARUBND PARGP SCALE OFFSET DERCOM'.split()
PAR_EXTRA = ['TIETO', 'PRIOR', 'WEIGHT']          # optional columns carried on self.par
PARGP_COLS = 'PARGPNME INCTYP DERINC DERINCLB FORCEN DERINCMUL DERMTHD'.split()
PARGP_OPT = 'SPLITTHRESH SPLITRELDIFF SPLITACTION'.split()
OBS_COLS = 'OBSNME OBSVAL WEIGHT OBGNME'.split()
PRIOR_COLS = 'PINME EQ WEIGHT OBGNME'.split()

ADJUSTABLE = ('log', 'none')
# operators and whitespace; a sign directly after an exponent (1e-3, 2.5E+02) is part of the number
_EQ_SPLIT = re.compile(r'[\s()*=/]+|(?<![0-9][eE])[-+]')


def _clean(s):
    return s.astype(str).str.strip().str.lower()


def _is_storage(names):
    return names.str.startswith('ss') | names.str.startswith('sy')


def _empty(cols):
    return pd.DataFrame(columns=cols)


def _append(old, new):
    """concat that keeps `new`'s dtypes when `old` is still the empty placeholder."""
    if len(old) == 0:
        return new.reset_index(drop=True)
    return pd.concat([old, new], ignore_index=True)


def equation_params(eq):
    """Parameter names referenced by a prior-information equation."""
    return [t for t in _EQ_SPLIT.split(str(eq).lower()) if t and t != 'log' and not is_number(t)]


class Pst:
    def __init__(self, pestmode='estimation', ss=False):
        self.pestmode = normalize_mode(pestmode)
        self.ss = ss                    # steady state: drop storage (ss*/sy*) parameters and groups
        self.comments = []              # '# ...' lines written after 'pcf'
        self.control = {}               # user values for every control-style section, flat
        self.use_svd = True
        self.par = _empty(PAR_COLS)
        self.pargp = _empty(PARGP_COLS)
        self.obs = _empty(OBS_COLS)
        self.prior = _empty(PRIOR_COLS)
        self.tpl = []                   # (template file, model input file)
        self.ins = []                   # (instruction file, model output file)
        self.cmd = []                   # model command lines
        self.pestpp = []                # (key, value) for ++key(value) lines
        self.raw_sections = {}          # sections kept verbatim (predictive analysis, pareto)
        self.obsgp_order = []           # preferred observation-group order (from a read pst)
        self.obs_cov = {}               # observation group -> covariance matrix file
        self.version = 1                # control file format: 1 classic, 2 PEST++ external tables
        self._auto_labels = set()       # prior labels generated by validate() from PRIOR/WEIGHT

    # ------------------------------------------------------------------ counts
    @property
    def npar(self):
        return len(self.par)

    @property
    def nobs(self):
        return len(self.obs)

    @property
    def npargp(self):
        return len(self.pargp)

    @property
    def nprior(self):
        return len(self.prior)

    @property
    def obsgp(self):
        used = list(dict.fromkeys(self.obs['OBGNME']))
        if self.nprior:
            used += [g for g in dict.fromkeys(self.prior['OBGNME']) if g not in used]
        return [g for g in self.obsgp_order if g in used] + [g for g in used if g not in self.obsgp_order]

    @property
    def nobsgp(self):
        return len(self.obsgp)

    @property
    def counts(self):
        return {'npar': self.npar, 'nobs': self.nobs, 'npargp': self.npargp, 'nprior': self.nprior,
                'nobsgp': self.nobsgp, 'ntplfle': len(self.tpl), 'ninsfle': len(self.ins),
                'pestmode': self.pestmode}

    # ------------------------------------------------------------------ control
    def set_control(self, values):
        """Set control-style values from a dict or a CONTROL sheet (NAME/VALUE columns)."""
        if isinstance(values, pd.DataFrame):
            df = values.iloc[:, :4].copy()
            df.columns = ['LINE', 'NAME', 'DEFAULT', 'VALUE'][:df.shape[1]]
            values = {str(r.NAME).strip().lower(): r.VALUE
                      for r in df.dropna(subset=['NAME', 'VALUE']).itertuples()}
        for k, v in values.items():
            k = str(k).strip().lower()
            if k == 'pestmode':
                self.pestmode = normalize_mode(v)
            elif k in COMPUTED:
                warnings.warn(f'control value {k}={v!r} ignored; it is computed from the tables')
            elif k not in FIELD_SECTION:
                warnings.warn(f'unknown control variable {k!r} ignored')
            elif fmt(v) != '':
                self.control[k] = _num(v) if isinstance(v, str) else v   # csv gives strings

    # ------------------------------------------------------------------ tables
    def add_pargp(self, df):
        df = df.dropna(subset=PARGP_COLS).copy()
        df['PARGPNME'] = _clean(df['PARGPNME'])
        if self.ss:
            df = df[~_is_storage(df['PARGPNME'])]
        cols = PARGP_COLS + [c for c in PARGP_OPT if c in df and df[c].notna().all()]
        self.pargp = _append(self.pargp, df[cols]).drop_duplicates('PARGPNME')

    def add_par(self, df):
        df = df.dropna(subset=PAR_COLS).copy()
        for c in ('PARNME', 'PARTRANS', 'PARGP'):
            df[c] = _clean(df[c])
        if self.ss:
            df = df[~_is_storage(df['PARNME'])]
        cols = PAR_COLS + [c for c in PAR_EXTRA if c in df]
        self.par = _append(self.par, df[cols])

    def add_tied(self, df):
        """Two columns: tied parameter name, parameter it is tied to.

        Listed parameters become PARTRANS 'tied'; a row tying a parameter to itself is ignored.
        """
        tied = df.iloc[:, :2].dropna()
        names, targets = _clean(tied.iloc[:, 0]), _clean(tied.iloc[:, 1])
        lookup = {n: t for n, t in zip(names, targets) if n != t}
        if 'TIETO' not in self.par:
            self.par['TIETO'] = pd.Series(None, index=self.par.index, dtype=object)
        hit = self.par['PARNME'].isin(lookup)
        missing = set(lookup) - set(self.par.loc[hit, 'PARNME'])
        if missing:
            warnings.warn(f'tied table names parameters that were not added: {sorted(missing)[:5]}')
        self.par.loc[hit, 'TIETO'] = self.par.loc[hit, 'PARNME'].map(lookup)
        self.par.loc[hit, 'PARTRANS'] = 'tied'

    def add_obs(self, df, weight_factor=1.0):
        df = df.dropna(subset=OBS_COLS).copy()
        df['OBSNME'] = _clean(df['OBSNME'])
        df['OBGNME'] = _clean(df['OBGNME'])
        df['WEIGHT'] = df['WEIGHT'] * weight_factor
        self.obs = _append(self.obs, df[OBS_COLS])

    def add_prior(self, df):
        """Explicit prior information (PINME, EQ, WEIGHT, OBGNME); any rows switch to regularisation mode."""
        df = df.dropna(subset=PRIOR_COLS).copy()
        if df.empty:
            return
        self.pestmode = 'regularisation'
        for c in ('PINME', 'EQ', 'OBGNME'):
            df[c] = _clean(df[c])
        self.prior = _append(self.prior, df[PRIOR_COLS])

    def add_obsgp(self, df):
        """Observation groups with optional covariance files (OBGNME, COVFILE); sets the group order."""
        df = df.dropna(subset=['OBGNME']).copy()
        df['OBGNME'] = _clean(df['OBGNME'])
        self.obsgp_order = list(dict.fromkeys(df['OBGNME']))
        if 'COVFILE' in df:
            self.obs_cov.update({g: fmt(f) for g, f in zip(df['OBGNME'], df['COVFILE']) if fmt(f)})

    def add_io(self, df):
        """Rows of (type, in, out): tpl/ins pairs, or cmd with the command in the second column."""
        for r in df.itertuples(index=False):
            t = fmt(r[0]).lower()
            if t == 'tpl':
                self.tpl.append((fmt(r[1]), fmt(r[2])))
            elif t == 'ins':
                self.ins.append((fmt(r[1]), fmt(r[2])))
            elif t == 'cmd':
                self.cmd.append(fmt(r[1]))

    def add_tpl(self, tpl, model_in):
        self.tpl.append((tpl, model_in))

    def add_ins(self, ins, model_out):
        self.ins.append((ins, model_out))

    def set_command_line(self, cmd):
        self.cmd = [cmd]

    def add_pp(self, df):
        """PEST++ options from the first two columns (name, value); blank values are skipped."""
        for r in df.itertuples(index=False):
            k, v = fmt(r[0]), r[1]
            if not k or fmt(v) == '':
                continue
            if isinstance(v, (float, np.floating)) and float(v).is_integer():
                v = int(v)
            self.pestpp.append((k, fmt(v)))

    def add_comment(self, table=None, comment=''):
        """Free-text header comments; a one-column table adds a line per cell, wider tables are tabulated."""
        if comment:
            self.comments += [c.rstrip() for c in str(comment).splitlines()]
        if table is not None:
            if table.shape[1] == 1:
                self.comments += [fmt(v) for v in table.iloc[:, 0] if fmt(v)]
            else:
                self.comments += table_lines(table, header=True)

    def fill_parval(self, parfile, real=None):
        """Replace PARVAL1 with the values in a PEST .par file or a PESTPP-IES ensemble (see read_par)."""
        vals = read_par(parfile, real)
        hit = self.par['PARNME'].isin(vals.index)
        missing = self.par.loc[~hit, 'PARNME']
        if len(missing):
            warnings.warn(f'{len(missing)} parameters not in {parfile}: {list(missing[:5])}...')
        self.par.loc[hit, 'PARVAL1'] = self.par.loc[hit, 'PARNME'].map(vals['PARVAL1']).values

    # ------------------------------------------------------------------ validation
    def validate(self):
        """Make the tables mutually consistent; raise on anything PEST would reject."""
        if self.npar == 0:
            raise ValueError('no parameters; add parameter data first')
        if self.nobs == 0:
            raise ValueError('no observations; add observation data first')
        for name, col in (('parameter', self.par['PARNME']), ('observation', self.obs['OBSNME'])):
            dup = col[col.duplicated()].unique()
            if len(dup):
                raise ValueError(f'duplicate {name} names: {list(dup[:10])}')
        self._resolve_tied()
        self._filter_pargp()
        self._build_prior()
        self._check_bounds()
        if not self.tpl or not self.ins:
            raise ValueError('need at least one template and one instruction file')
        if not self.cmd:
            raise ValueError('model command line not set')
        return self

    def _check_bounds(self):
        """PEST refuses to start with an adjustable parameter outside its bounds; say so early."""
        par = self.par
        v, lb, ub = (pd.to_numeric(par[c], errors='coerce') for c in ('PARVAL1', 'PARLBND', 'PARUBND'))
        out = par['PARTRANS'].isin(ADJUSTABLE) & ((v < lb) | (v > ub))
        if out.any():
            warnings.warn(f'{int(out.sum())} adjustable parameters have PARVAL1 outside their bounds: '
                          f'{list(par.loc[out, "PARNME"][:5])}...')

    def _resolve_tied(self):
        par = self.par
        tied = par['PARTRANS'] == 'tied'
        if not tied.any():
            return
        if 'TIETO' not in par:
            raise ValueError('tied parameters present but no TIETO column / tied table')
        par['TIETO'] = par['TIETO'].where(par['TIETO'].notna(), None)
        par.loc[tied, 'TIETO'] = _clean(par.loc[tied, 'TIETO'])
        trans = par.set_index('PARNME')['PARTRANS']
        target = par.loc[tied, 'TIETO'].map(trans)
        bad = par.loc[tied][target.isna().values]
        if len(bad):
            raise ValueError(f'tied parameters whose target is missing: '
                             f'{list(zip(bad.PARNME, bad.TIETO))[:10]}')
        chain = par.loc[tied][(target == 'tied').values]
        if len(chain):
            raise ValueError(f'parameters tied to a tied parameter: {list(chain.PARNME[:10])}')
        to_fix = par.loc[tied][(target == 'fixed').values]
        if len(to_fix):
            print(f'{len(to_fix)} parameters tied to fixed parameters; setting them fixed too')
            par.loc[to_fix.index, 'PARTRANS'] = 'fixed'

    def _filter_pargp(self):
        used = list(dict.fromkeys(self.par['PARGP']))
        missing = [g for g in used if g not in set(self.pargp['PARGPNME'])]
        if missing:
            raise ValueError(f'parameter groups without a definition: {missing}')
        self.pargp = self.pargp[self.pargp['PARGPNME'].isin(used)].reset_index(drop=True)

    def _build_prior(self):
        # drop what a previous validate() generated so this is idempotent
        prior = [self.prior[~self.prior['PINME'].isin(self._auto_labels)]]
        self._auto_labels = set()
        if self.pestmode == 'regularisation' and {'PRIOR', 'WEIGHT'} <= set(self.par):
            auto = self._auto_prior()
            self._auto_labels = set(auto['PINME'])
            prior.append(auto)
        # skip empty frames: pandas 2.x warns that they will stop influencing result dtypes
        prior = [df for df in prior if len(df)]
        prior = pd.concat(prior, ignore_index=True) if prior else _empty(PRIOR_COLS)
        dup = prior['PINME'][prior['PINME'].duplicated()].unique()
        if len(dup):
            raise ValueError(f'duplicate prior information labels: {list(dup[:10])}')
        adjustable = set(self.par.loc[self.par['PARTRANS'].isin(ADJUSTABLE), 'PARNME'])
        # astype(bool): an empty object-dtype mask would select columns, not rows
        ok = prior['EQ'].map(lambda eq: all(p in adjustable for p in equation_params(eq))).astype(bool)
        if (~ok).any():
            dropped = prior.loc[~ok, 'PINME']
            print(f'dropping {len(dropped)} prior equations that reference fixed, tied or '
                  f'missing parameters: {list(dropped[:5])}...')
        self.prior = prior[ok].reset_index(drop=True)

    def _auto_prior(self):
        """Regularisation equations from the PRIOR / WEIGHT columns of the parameter table.

        PRIOR is either a preferred value or the name of another parameter the
        parameter should equal.  Log-transformed parameters get log() equations.
        """
        p = self.par.dropna(subset=['PRIOR', 'WEIGHT'])
        p = p[(pd.to_numeric(p['WEIGHT'], errors='coerce') > 0) & p['PARTRANS'].isin(ADJUSTABLE)]
        rows = []
        for r in p.itertuples():
            islog = r.PARTRANS == 'log'
            name, target = r.PARNME, fmt(r.PRIOR).lower()
            if is_number(target):
                v = float(target)
                if islog:
                    if v <= 0:
                        warnings.warn(f'{name}: non-positive prior value {v} for a log parameter; skipped')
                        continue
                    eq = f'1.0 * log({name}) = {np.log10(v):{".11g"}}'
                else:
                    eq = f'1.0 * {name} = {v:{".11g"}}'
            elif islog:
                eq = f'1.0 * log({name}) - 1.0 * log({target}) = 0'
            else:
                eq = f'1.0 * {name} - 1.0 * {target} = 0'
            rows.append((name, eq, r.WEIGHT, ('regul' + r.PARGP)[:12]))
        return pd.DataFrame(rows, columns=PRIOR_COLS)


# ---------------------------------------------------------------------- helpers
def read_par(parfile, real=None):
    """Parameter values as a DataFrame indexed by lower-case parameter name.

    `parfile` is a PEST .par file (name value scale offset) or a PESTPP-IES ensemble
    (case.N.par.csv), in which case `real` picks the realization: a name such as
    'base' or '17', 'best' (lowest phi in case.phi.actual.csv next to it), or None
    for 'base'.
    """
    if is_ensemble(parfile):
        ens = read_ensemble(parfile)
        row = ens.loc[select_realization(ens, parfile, real)]
        return pd.DataFrame({'PARVAL1': pd.to_numeric(row)}).rename_axis('PARNME')
    df = pd.read_csv(parfile, sep=r'\s+', skiprows=1, header=None,
                     names=['PARNME', 'PARVAL1', 'SCALE', 'OFFSET'])
    df['PARNME'] = _clean(df['PARNME'])
    return df.set_index('PARNME')


def is_ensemble(path):
    """True for a PESTPP-IES ensemble csv (first column real_name)."""
    with open(path) as f:
        return f.readline().strip().lower().startswith('real_name')


def read_ensemble(path):
    """A PESTPP-IES ensemble csv (case.N.par.csv / case.N.obs.csv): rows are realizations."""
    df = pd.read_csv(path, index_col=0)
    df.index = df.index.astype(str).str.strip().str.lower()
    df.columns = [str(c).strip().lower() for c in df.columns]
    return df


_ENSEMBLE_NAME = re.compile(r'^(?P<case>.+?)\.(?P<iter>\d+)\.(par|obs)\.csv$', re.I)


def best_realization(path):
    """Realization with the lowest phi for ensemble file `path`, from case.phi.actual.csv next to it."""
    m = _ENSEMBLE_NAME.match(os.path.basename(path))
    if not m:
        raise ValueError(f'cannot tell case and iteration from {os.path.basename(path)!r}; '
                         f'expected case.N.par.csv')
    phi_file = os.path.join(os.path.dirname(path), f"{m['case']}.phi.actual.csv")
    if not os.path.exists(phi_file):
        raise FileNotFoundError(f"'best' needs {phi_file}")
    phi = pd.read_csv(phi_file)
    phi.columns = [str(c).strip().lower() for c in phi.columns]
    row = phi[phi['iteration'] == int(m['iter'])]
    if row.empty:
        raise ValueError(f"iteration {m['iter']} not in {phi_file}")
    stats = {'iteration', 'total_runs', 'mean', 'standard_deviation', 'min', 'max'}
    reals = row.iloc[0].drop(labels=[c for c in phi.columns if c in stats])
    return str(pd.to_numeric(reals).idxmin())


def select_realization(ens, path, real=None):
    if real is None:
        real = 'base'
        if real not in ens.index:
            raise ValueError(f"no 'base' realization in {path}; give one of {list(ens.index[:10])}...")
    elif str(real).lower() == 'best':
        real = best_realization(path)
    real = str(real).strip().lower()
    if real not in ens.index:
        raise ValueError(f'realization {real!r} not in {path}; available: {list(ens.index[:10])}...')
    return real


def read_obs_ensemble(path, real=None, pst=None):
    """One realization of a PESTPP-IES observation ensemble as MODELLED (+ RESIDUAL and GROUP with a Pst)."""
    ens = read_ensemble(path)
    row = pd.to_numeric(ens.loc[select_realization(ens, path, real)])
    df = pd.DataFrame({'MODELLED': row}).rename_axis('NAME')
    if pst is not None:
        obs = pst.obs.set_index('OBSNME')
        df['RESIDUAL'] = pd.to_numeric(obs['OBSVAL']).reindex(df.index) - df['MODELLED']
        df['WEIGHT'] = pd.to_numeric(obs['WEIGHT']).reindex(df.index)
        df['GROUP'] = obs['OBGNME'].reindex(df.index)
    return df


def read_res(resfile):
    """A PEST .res / .rei residuals file as a DataFrame indexed by lower-case observation name."""
    df = pd.read_csv(resfile, sep=r'\s+')
    df.columns = [c.strip().upper() for c in df.columns]
    df['NAME'] = _clean(df['NAME'])
    return df.set_index('NAME')


def table_lines(df, header=False, numeric_right=True):
    """A DataFrame as aligned, whitespace-delimited text lines (no index)."""
    cols = list(df.columns)
    cells = [[fmt(v) for v in df[c]] for c in cols]
    # right-align by content, not dtype, so a column reads the same whatever produced it
    is_num = [numeric_right and any(col) and all(is_number(s) for s in col if s) for col in cells]
    widths = [max([len(str(c)) if header else 0] + [len(s) for s in col]) for c, col in zip(cols, cells)]
    lines = []
    if header:
        lines.append('  '.join(f'{str(c):<{w}}' for c, w in zip(cols, widths)).rstrip())
    for i in range(len(df)):
        lines.append('  '.join(f'{col[i]:>{w}}' if right else f'{col[i]:<{w}}'
                               for col, w, right in zip(cells, widths, is_num)).rstrip())
    return lines
